name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.16
      -
        name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      -
        name: Run build
        run: go build .
      -
        name: Run vet & lint
        run: |
          go vet .
          golint .
